# Step 3: Data Preprocessing

## Objectives
- Load and validate the original dataset.
- Separate input features and target variable.
- Inspect feature variance and data quality.
- Split data into training and testing sets.
- Prepare preprocessing steps for machine learning.

In [18]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/phishing_dataset.csv")

print("Dataset shape:", df.shape)
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

display(df.head())

Dataset shape: (39676, 17)
Missing values: 0
Duplicate rows: 0

,url,label,url_length,domain_length,path_length,query_length,num_dots,num_hyphens,num_digits,num_special_chars,has_ip,is_https,has_php,has_html,has_exe,num_subdomains,tld_length
0,http://olxtos.com,0,17,6,0,0,1,0,0,0,0,0,0,0,0,0,3
1,https://fnvimoyvwkbxbmczlqus.supabase.co/stora...,1,90,8,50,0,3,0,7,0,0,1,0,0,0,1,2
2,http://loobygamesonline.com,0,27,16,0,0,1,0,0,0,0,0,0,0,0,0,3
3,http://simbhaolisugars.in/bins/sora.x86,1,39,15,14,0,2,0,2,0,0,0,0,0,0,0,2
4,http://found.com,0,16,5,0,0,1,0,0,0,0,0,0,0,0,0,3

In [19]:
# Input features
X = df.drop(columns=["url", "label"])

# Target variable
y = df["label"]

print("Feature matrix shape:", X.shape)
print("Target shape:", y.shape)

print("\nFeature columns:")
print(X.columns.tolist())

print("\nTarget classes:")
print(y.value_counts())

Feature matrix shape: (39676, 15)
Target shape: (39676,)

Feature columns:
['url_length', 'domain_length', 'path_length', 'query_length', 'num_dots', 'num_hyphens', 'num_digits', 'num_special_chars', 'has_ip', 'is_https', 'has_php', 'has_html', 'has_exe', 'num_subdomains', 'tld_length']

Target classes:
label
0    19838
1    19838
Name: count, dtype: int64

In [20]:
feature_variance = X.nunique(dropna=False).sort_values()

print("Number of unique values in each feature:")
display(feature_variance.to_frame("Unique Values"))

constant_features = feature_variance[
    feature_variance <= 1
].index.tolist()

print("Constant features:", constant_features)

Number of unique values in each feature:

                   Unique Values
has_ip                         1
has_html                       2
is_https                       2
has_php                        2
has_exe                        2
num_subdomains                 7
num_dots                      12
tld_length                    13
num_hyphens                   19
domain_length                 31
num_special_chars             35
num_digits                    68
query_length                  69
path_length                  152
url_length                   179

Constant features: ['has_ip']

In [21]:
# Remove constant features from the input data
X = X.drop(columns=constant_features)

print("Features after removing constant columns:", X.shape)
print("Remaining constant features:", X.columns[X.nunique() <= 1].tolist())

Features after removing constant columns: (39676, 14)
Remaining constant features: []

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("\nTraining target distribution:")
display(y_train.value_counts())

print("\nTesting target distribution:")
display(y_test.value_counts())

Training features: (31740, 14)
Testing features: (7936, 14)

Training target distribution:

label
1    15870
0    15870
Name: count, dtype: int64

Testing target distribution:

label
0    3968
1    3968
Name: count, dtype: int64

In [23]:
print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

print(
    "Overlap in original row indices:",
    len(X_train.index.intersection(X_test.index))
)

Training rows: 31740
Testing rows: 7936
Overlap in original row indices: 0

In [24]:
print("X shape:", X.shape)
print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)
print("Remaining constant features:",
      X.columns[X.nunique() <= 1].tolist())

X shape: (39676, 14)
Training shape: (31740, 14)
Testing shape: (7936, 14)
Remaining constant features: []